### ISSUE TITLE
Completes hito 8

### ISSUE THREAD

**Issue by crisconru** [Phyton-es-mi-typo/tyempo#21]
## Merelo requirements

> Esencialmente, se trata de continuar con el desarrollo de las clases anteriores, usando todas las técnicas posibles para asegurarse de que el diseño de las clases captura, en tiempo de compilación, todos los posibles errores (o simplemente no permite que se produzcan).
> Se tendrá que añadir una clave más, `linter`, a `agil.yaml`, con el nombre del linter que se ha usado para comprobar el código. La ejecución de este linter, como cualquier otra tarea asociada al proyecto, tendrá que añadirse como tarea para el sistema de gestor de tareas, usando, por ejemplo, el target “`check`” (por ejemplo, que haya que ejecutar `make check` para ejecutar el linter con las opciones correspondientes).

## Tasks

- [ ] Add `linter` to `agil.yaml` -> We are going to use `flake8`
- [ ] Create task `check` in the task runner -> We are going to use `Mask`
    - [ ] Create `maskfile.md` to execute `Mask` tasks
    - [ ] Create the `check` task
