### ISSUE TITLE
Completes Hito 9

### ISSUE THREAD

**Issue by crisconru** [Phyton-es-mi-typo/tyempo#23]
## Merelo Requirements

> A partir del diseño creado en la anterior actividad, y siguiendo las prácticas de uso de los issues (y su cierre desde un commit), crear una o varias clases básicas que correspondan a la misma entidad (según el dominio del problema que se haya elegido), por supuesto incluyendo los tests correspondientes. Los tests se ejecutarán en local, por lo pronto. Pasamos ya a la versión 9.x.x del proyecto.
> 
> Se editará el fichero agil.yaml añadiéndole, además, la siguiente clave (sin borrar las anteriores):
> 
> ```yaml
> test:
>     - tests/fichero-test.jl
> aserciones: "@test"
> ```
> En vez de este nombre ficticio, se usará el nombre del fichero de construcción que se haya usado para ejecutar los tests, que tendrá que estar presente en el repositorio.

## Tasks

We are beginning to define tests

- [ ] Create one or more classes which corresponds to the same entity and add their tests.
- [ ] Add tests to the task runner.
- [ ] Edit `agil.yaml` including `test` & `aserciones`
