### ISSUE TITLE
Complete hito 11

### ISSUE THREAD

**Issue by crisconru** [Phyton-es-mi-typo/tyempo#26]
## Merelo requirements

Añadir al repositorio que se ha hecho en el hito anterior integración continua con Travis, al menos, y adicionalmente con cualquier otro sistema.

El repositorio tendrá que incluir el badge de Travis y este tendrá que estar en verde para aceptar el PR. El fichero de configuración de Travis tendrá que estar también presente, como es natural.

## Tasks

- [x] No olvidarse de cerrar los issues #16 y #18 a parte de este de manera automática en el PR a main
    - [x] Debe de aparecer en el principio `Close, #16, Close #18, Close #26` 
- [x] Añadir el badge de Travis
- [x] Que Travis no pete porque sino, no pasa el hito
